name: tagging

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  tag-version:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Update major tag
        run: |
          MAJOR_VERSION=$(git describe --tags | grep -o "v[0-9]*")
          git config --global user.name 'CI'
          git config --global user.email 'CI@users.noreply.github.com'
          git tag -afm "Updated tag $MAJOR_VERSION to $(git describe --tags)" $MAJOR_VERSION
          git push --tags --force
